org: interiorwildebeest
console: true
service: datasync
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'dynamoDB:*'
          Resource: '*'

        - Effect: Allow
          Action: 'documentDB:*'
          Resource: '*'

functions:
  connect:
    handler: "src/handlers/connection.handleConnection"
    environment:
      CONNECTION_TABLE: connectionTable
    events:
      - websocket:
          route: $connect

  disconnect:
    handler: "src/handlers/connection.handleDisconnection"
    environment:
      CONNECTION_TABLE: connectionTable
    events:
      - websocket:
          route: $disconnect

  default:
    handler: "src/handlers/message.routingHandler"
    environment:
      CONNECTION_TABLE: connectionTable
      DOCUMENTS_TABLE: docsTable
    events:
      - websocket:
          route: $default

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: connectionTable
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    docsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: docsTable
        AttributeDefinitions:
          - 
            AttributeName: documentId
            AttributeType: S
        KeySchema:
          - 
            AttributeName: documentId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-esbuild
